### ISSUE TITLE
Weird behavior of FloatingActionButton after dismissing Snackbar

### ISSUE THREAD

**Issue by ivixor** [antoniolg/MaterializeYourApp#7]
Hi.

After dismissing Snackbar by swiping it out FloatingActionButton remains on elevated position.
Steps-To-Reproduce:
1. Click on FAB.
2. Swipe-to-dismiss Snackbar.

I see all widgets in your demo are from support design library, so I am curious is there any way to make it move down after dismissing Snackbar?

Thank you.

P.S. Sorry for my English. I hope you understand me.

**Comment by antoniolg** [comment]
Perfectly! I'm no native either, so probably my English is even worse :smile: . That's probably a bug in the design library. There's been a couple of updates since I last updated this repo, so hopefully that (and some other) problems have been fixed. I'll try to find some time to update it, but feel free to fix it and PR if you feel like.

**Comment by antoniolg** [comment]
This is fixed in latest reviews of the design support library.
